### ISSUE TITLE
Jobs never complete

### ISSUE THREAD

**Issue by socrates-hlapolosa** [camunda-community-hub/kafka-connect-zeebe#143]
I'm running a self hosted confluent and zeebee environment. But for both examples, everything works except i never get to end state, always get stuck on the step just prior to ending, and no apparent error.

Any Idea why this could be?

**Comment by berndruecker** [comment]
Hey @socrates-hlapolosa - sorry that I have missed the issue here - could you ask in the forum instead? https://forum.camunda.io/
Feel free to ping me there if there is no answer!
