### ISSUE TITLE
Update to Zeebe 1.0

### ISSUE THREAD

**Issue by danshapir** [camunda-community-hub/kafka-connect-zeebe#56]
As zeebe v1 is finally out and had some breaking changes, I was wondering is this compatible with zeebe v1?

If so, what needs to be done?

**Comment by berndruecker** [comment]
It is not yet - but I am working on it now - I will hijack this issue for it :-)

**Comment by berndruecker** [comment]
Looks good on master now - I will do some more severe testing with it and release a new version hopefully next week (that should also go to Confluent Hub)

**Comment by berndruecker** [comment]
waiting for the release pipeline to be activated (https://github.com/camunda-community-hub/infrastructure/pull/17)

**Comment by celanthe** [comment]
Hi @berndruecker! I just merged your PR, so you should be able to start the release pipeline! Please let me know if you have any problems. I am happy to help. 

If you get stuck, you can also refer to [the release process documentation](https://github.com/camunda-community-hub/community/blob/main/RELEASE.MD) as well. :)

**Comment by berndruecker** [comment]
@celanthe I just published 0.31.0 - please release the staged Artifact to Maven Central. Thx

**Comment by berndruecker** [comment]
https://github.com/camunda-community-hub/kafka-connect-zeebe/releases/tag/0.31.0

**Comment by celanthe** [comment]
@berndruecker Thank you for the assignment! I just released this version to Maven Central. You should see it visible there within a few hours! :)
