### ISSUE TITLE
Failed to deploy artifacts: Could not transfer artifact, status: 401 Unauthorized 

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/kafka-connect-zeebe#72]
This is wired - it still worked on January 16th, but not today - there were any specific changes I am aware of (I tried something today but rolled it back as it is was not the problem): https://github.com/camunda-community-hub/kafka-connect-zeebe/runs/4957329187?check_suite_focus=true

the target URL seems to be correct: https://oss.sonatype.org/content/repositories/snapshots/io/zeebe/kafka-connect-zeebe/0.32.1-SNAPSHOT/

@celanthe: Any idea? Any credentials removed recently?

**Comment by berndruecker** [comment]
It is also correctly added here: https://github.com/camunda-community-hub/infrastructure/blob/master/terraform/github/repositories.tf

**Comment by celanthe** [comment]
@berndruecker The only thing I can think of that changed recently is that there was a new update to Artifactory in the CCH made by Infra. Will DM you and see if that might be the cause of this!

**Comment by berndruecker** [comment]
What I don't understand is why this "io.camunda" Artifact actually ends up on `oss.sonatype.org` instead of `s01.oss.sonatype.org` - but it worked till 2 weeks ago. Happy to take ideas
