### ISSUE TITLE
Values are cached when concat function from json path used

### ISSUE THREAD

**Issue by aanodin** [camunda-community-hub/kafka-connect-zeebe#96]
We tried to use the following statement for generating message name for zeebe:
`"message.path.messageName": "concat(\"ChargeOrder_\", $.data.chargeOrderEvent.chargingResult)",`

## Expected behaviour
We can have two values in data.chargeOrderEvent.chargingResult: SUCCESS and FAILED. So we expected two different message names to be published to zeebe: ChargeOrder_SUCCESS and ChargeOrder_FAILED.

## Actual behaviour
kafka-connect-zeebe cached the message name so it was sending always one of two possible values (e.g. ChargeOrder_SUCCESS) and never the second one. 

## Details
The project uses an old version of jayway jsonpath from 2020 (2.4.0). It contains a bug fixed a year ago: https://github.com/json-path/JsonPath/issues/680

**Comment by berndruecker** [comment]
Thanks @aanodin for the detailed issue. 
Do you know if updating json-path would already fix the issue, or would something additional to disable caching be required?

Would you possibly even be willing to provide a PR?

**Comment by aanodin** [comment]
> Related to #95 (maybe fixed by it?)

Yes, this should fix the issue, thanks. 
Seems that nothing is needed in addition.

**Comment by berndruecker** [comment]
Do you want to test if this works now by doing your own build on the latest main?

**Comment by aanodin** [comment]
@berndruecker we have tested the same fix on our local build, it works.

**Comment by berndruecker** [comment]
Awesome - thanks!

**Comment by berndruecker** [comment]
Good timing by the way - just released https://github.com/camunda-community-hub/kafka-connect-zeebe/releases/tag/0.40.1
